[package]
name = "type-level-logic"
version = "0.1.0"
authors = ["Sean Leffler <sean@errno.com>"]

[dependencies]
type-operators = { git = "https://github.com/sdleffler/type-operators-rs.git" }

[features]
default = []
specialization = ["type-operators/specialization"]
nightly = ["specialization"]
